dataBase:
  read:
    host: "184.168.122.58"
    dataBaseName: "paxful"
    port: "3306"
    userName: "paxful"
    password: "SSfxxG5RKHNL3nRG"
  write:
    host: "184.168.122.58"
    dataBaseName: "paxful"
    port: "3306"
    userName: "paxful"
    password: "SSfxxG5RKHNL3nRG"